### ISSUE TITLE
Print Ordering vereinheitlichen

### ISSUE THREAD

**Issue by alexdobry** [THK-ADV/mocogi#41]
damit keine Merge Konflikte bei sowas wie
```
po_optional:
  - study_program: study_program.inf_wi5
  - study_program: study_program.inf_wi4
    instance_of: module.aacd9661-dba7-40e5-b98d-4e7019e18365
    instance_of: module.aacd9661-dba7-40e5-b98d-4e7019e18365
    part_of_catalog: false
    part_of_catalog: false
    recommended_semester:
    recommended_semester:
```
entstehen
